### ISSUE TITLE
Why status 500

### ISSUE THREAD

**Issue by johnzielke** [SwaggerTagger/octo-tagger-frontend#6]
In [src\components\RegisterComponent.vue:72](https://github.com/SwaggerTagger/octo-tagger-frontend/blob/ff177d5ab679a663d00047ef64b8237dc15a1805/src/components/RegisterComponent.vue#L70-L73) there is the following code:
`    isUnauthorized() {
      return this.registered.reason
      && this.registered.reason.status === 500
    },`
Why is this status code 500 ? Shouldn't it be 401?

**Comment by georggrab** [comment]
backend returns 500 on
- incomplete form input
- invalid form input (email)
I agree that `isUnauthorized` is a horribly chosen name for this (will fix this), but functionality wise everything works as expected
